from __future__ import annotations

import argparse
import ipaddress
import os
import subprocess
from pathlib import Path


DEFAULT_HOSTS = ("192.168.1.99",)


def _is_private_ipv4(value: str) -> bool:
    try:
        address = ipaddress.ip_address(value.strip())
    except ValueError:
        return False
    return (
        address.version == 4
        and address.is_private
        and not address.is_loopback
        and not address.is_link_local
    )


def _append_host(hosts: list[str], value: str) -> None:
    value = value.strip()
    if _is_private_ipv4(value) and value not in hosts:
        hosts.append(value)


def _split_hosts(value: str) -> list[str]:
    return [part.strip() for part in value.replace(";", ",").split(",") if part.strip()]


def _active_windows_ipv4_addresses() -> list[str]:
    command = (
        "Get-NetIPAddress -AddressFamily IPv4 | "
        "Where-Object { $_.IPAddress -ne '127.0.0.1' -and $_.IPAddress -notlike '169.254.*' } | "
        "ForEach-Object { $_.IPAddress }"
    )
    try:
        output = subprocess.check_output(
            ["powershell", "-NoProfile", "-Command", command],
            text=True,
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.CalledProcessError):
        return []
    return [line.strip() for line in output.splitlines() if line.strip()]


def collect_lan_hosts(extra_hosts: list[str] | None = None) -> list[str]:
    hosts: list[str] = []
    for host in DEFAULT_HOSTS:
        _append_host(hosts, host)
    for host in _split_hosts(os.getenv("LIFEPIM_CADDY_EXTRA_HOSTS", "")):
        _append_host(hosts, host)
    for host in extra_hosts or []:
        _append_host(hosts, host)
    for host in _active_windows_ipv4_addresses():
        _append_host(hosts, host)
    return hosts


def build_caddyfile(hosts: list[str], upstream: str) -> str:
    http_hosts = ", ".join(f"http://{host}" for host in hosts)
    https_hosts = ", ".join(f"https://{host}" for host in hosts)
    return f"""# Generated by LifePIM Desktop startup.
# Includes active private IPv4 addresses so Wi-Fi and USB tether LAN sync both work.

{http_hosts} {{
\thandle /api/pocket/v1/* {{
\t\treverse_proxy {upstream}
\t}}

\thandle {{
\t\tredir https://{{host}}{{uri}} permanent
\t}}
}}

{https_hosts} {{
\trequest_body {{
\t\tmax_size 10MB
\t}}

\theader {{
\t\tX-Content-Type-Options nosniff
\t\tX-Frame-Options DENY
\t\tReferrer-Policy no-referrer
\t\tPermissions-Policy "camera=(), microphone=(), geolocation=()"
\t}}

\treverse_proxy {upstream} {{
\t\theader_up X-Forwarded-For {{remote_host}}
\t\theader_up X-Forwarded-Proto {{scheme}}
\t\theader_up X-Forwarded-Host {{host}}
\t}}
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Write the LifePIM Caddyfile for current LAN addresses.")
    parser.add_argument("--config", required=True, help="Path to Caddyfile to write.")
    parser.add_argument("--upstream", default="127.0.0.1:9741", help="Waitress upstream host:port.")
    parser.add_argument("--include", action="append", default=[], help="Additional private IPv4 address to include.")
    args = parser.parse_args()

    hosts = collect_lan_hosts(args.include)
    if not hosts:
        print("ERROR: No private IPv4 addresses found for Caddy.", flush=True)
        return 1

    config_path = Path(args.config)
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(build_caddyfile(hosts, args.upstream), encoding="utf-8")
    print("Updated Caddy hosts: " + ", ".join(hosts), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
