#!/usr/bin/python3
# coding: utf-8
# events_from_filelist.py
# creates events based on lists of files
# for fast calendar view of photos / files created

import os 
import sys

root_folder = os.path.abspath(os.path.dirname(os.path.abspath(__file__)) + os.sep + ".." )
pth = os.path.join(root_folder, 'src')
sys.path.append(pth)

import index as index 
import config as mod_cfg
import web_data as web
import events

def generate_events():
    print('Generating events from filelist')
    #fldr_list = web.get_folder_list(mod_cfg.folder_list_file)
    #print(fldr_list)
    init_calendar_folders()

    index_list = index.get_list_and_names_index_files()
    for row in index_list:
        create_events_for_index_file(row[0], row[1]) #fname, display_name
    
    #print(index_list)


def create_events_for_index_file(fname, display_name):
    print(events.dte() + ' creating events from filelist ' + display_name)
    lst = index.read_csv_to_list(fname)
    for line in lst[1:5000]:
        #print(line)
        op_file = events.get_calendar_filename_for_date(line[4][0:9])
        append_event_to_file(line, op_file)

def append_event_to_file(line, op_file):
    """
    save the list data from columns to output format 
    and append to the file
    fullFilename,name,path,size,date,
    """
    txt = ''
    txt += '"' + line[4] + '",'
    txt += '"File",'
    txt += '"' + line[0] + '",'
    txt += '"' + line[1] + ' (' + line[3] + ' bytes)' + '"\n'
    with open(op_file, 'a') as fop:
        fop.write(txt)




def init_calendar_folders():
    print('WARNING - all autogenerated calendar PCFile data will be wiped\nPress Enter to continue or Ctrl C')
    x = input()
    root_folder = events.get_root_event_folder()
    index.ensure_dir(root_folder)
    index.delete_files_in_folder(root_folder, 'events_*.csv')





generate_events()    