#!/usr/bin/python3
# coding: utf-8
# config.py

import os

# ----------------------------------------------------------------------------
# Folder Locations
# 

#user_folder = r'\\FANGORN\user\duncan\LifePIM_Data'
user_folder = r"D:\DATA_LLM\SAMPLE_DATA\lifepim_desktop_data"

logon_file = os.path.join(user_folder, 'configuration', 'lifepim.par')
data_folder = os.path.join(user_folder, 'DATA')
index_folder = os.path.join(user_folder, 'index')
calendar_folder = os.path.join(user_folder, 'calendar')
folder_list_file =  os.path.join(user_folder, 'configuration', 'folders.lis')
export_data_folder_base = os.path.join(user_folder, 'export_data')


#db_name = os.path.join(user_folder, 'DATA', 'SQL', 'lifepim.db')
db_name = os.path.join(user_folder, 'lifepim.db')

DB_FILE = db_name
print('DB_FILE = ' + DB_FILE)

# ----------------------------------------------------------------------------
# Table Definitions
#
# Note - all tables have columns specified below as well as standard metadata
# columns : 
#   id  = unique id of record, autogenerated - should be in column position 1
#   user_name   = TEXT username of person adding record, default to logged on user - 2nd to last column in table
#   rec_extract_date text = DATETIME record updated or inserted - last column in table
#
#  The DATA TYPE of all columns should be TEXT unless the name of the column changes it below
#  column name contains 'date' = DATETIME
#  column name contains 'amount', 'total', 'num_' = NUMBER
#  
table_def = [
	{'name':'lp_notes', 'route':'notes', 'display_name':'Notes', 'col_list':['title','content', 'project']},
	{'name':'lp_tasks', 'route':'tasks', 'display_name':'Tasks', 'col_list':['title','content', 'project', 'start_date', 'due_date']},
	{'name':'lp_events', 'route':'calendar', 'display_name':'Events', 'col_list':['title','content', 'event_date', 'remind_date', 'project']},

	{'name':'lp_goals', 'route':'goals', 'display_name':'Goals', 'col_list':['parent_goal_id', 'title','description', 'goal_date', 'remind_date', 'project']},
	{'name':'lp_how', 'route':'how', 'display_name':'How', 'col_list':['parent_how_id', 'title','description', 'project']},
	{'name':'lp_data', 'route':'data', 'display_name':'Data', 'col_list':['name','description', 'tbl_name', 'col_list', 'project']},
	{'name':'lp_files', 'route':'files', 'display_name':'Files', 'col_list':['filelist_name','path', 'file_type', 'project']},
	
]

"""
use the route value in config.py > table_def to decide which table the top tab uses
from the table name, also lookup the col_list to determine the select statement
Implement the tasks view, add, edit and delete using these parameters to directly
call the data.py > get_data, add_record, update_record, delete_record.
There should not be separate get_tasks, add_tasks in the data.py
"""

# ----------------------------------------------------------------------------
# Interface configuration

# Project list default
proj_list = ['Dev','Design','Fun','Games','Family','Car',
             'Business','Web','Home','Study','Health','Work',
             'RasbPI','AI','Support','Pers']


SIDE_TABS_GROUPS = [  # for possible sub folders
    { 'icon': '*', 'id': 'All', 'sub_list': 'All Projects'},
    { 'icon': '🔒', 'id': 'PERS', 'sub_list': 'Pers,Health,Home,Car,Family,Food'},
    { 'icon': '🎉', 'id': 'FUN', 'sub_list': 'games, travel, Music, movies, Books, Hobbies'},
    { 'icon': '💼', 'id': 'WORK', 'sub_list': 'Work,Business,Side Gigs,Commision'},
    { 'icon': '🛠️', 'id': 'MAKE', 'sub_list': 'Dev,Design,Web,RasbPI,AI,PC Support'},
    { 'icon': '👩🏻‍🎓', 'id': 'LEARN', 'sub_list': 'Study, Skills, Languages, Courses'},
]

SIDE_TABS = [  # Tabs down left side of LifePIM - any project goes into one of these groups
    { 'icon': '*', 'id': 'All', 'label': 'All Projects'},
    { 'icon': '', 'id': 'spacer', 'label': 'PERS'}, 

    #{ 'icon': '🔒', 'id': 'pers', 'label': 'Personal'},
    { 'icon': '💊', 'id': 'health', 'label': 'Health'}, 
    { 'icon': '👪', 'id': 'family', 'label': 'Family'}, 
    { 'icon': '🏚️', 'id': 'house', 'label': 'House'}, 
    { 'icon': '🌴', 'id': 'garden', 'label': 'Garden'}, 
    { 'icon': '🚗', 'id': 'car', 'label': 'Car'}, 

    { 'icon': '', 'id': 'fun', 'label': 'FUN'}, 

    { 'icon': '🎉', 'id': 'fun/events', 'label': 'Events'},  # note that top tabs separate movies,
    { 'icon': '🕹️', 'id': 'fun/games', 'label': 'Games'}, 
    { 'icon': '🍕', 'id': 'fun/food', 'label': 'Food'}, 

    { 'icon': '🏈', 'id': 'fun/sport', 'label': 'Sport'}, 
    { 'icon': '👣', 'id': 'fun/travel', 'label': 'Travel'}, 



    { 'icon': '', 'id': 'make', 'label': 'MAKE'}, 


    #{ 'icon': '🖥️', 'id': 'dev/Python', 'label': 'Python'}, 
    { 'icon': '📐', 'id': 'make/design', 'label': 'Design'},   # can be Art / Draw
    { 'icon': '🖋️', 'id': 'make/write', 'label': 'Writing'}, 
    #{ 'icon': '📐', 'id': 'design/programs', 'label': 'Program Design'}, 
    { 'icon': '🛠️', 'id': 'make/build', 'label': 'Build'}, 
    
    #{ 'icon': '📻', 'id': 'make/pc', 'label': 'PC'}, 

    { 'icon': '', 'id': 'spacer', 'label': 'WORK'}, 


    { 'icon': '💼', 'id': 'work/job', 'label': 'Job'}, 
    { 'icon': '💼', 'id': 'work/business', 'label': 'Business'}, 
    #{ 'icon': '💼', 'id': 'work/freelance', 'label': 'Freelance'}, 

    { 'icon': '👩🏻‍🎓', 'id': 'work/study', 'label': 'Study'}, 
    
    #{ 'icon': '🧰', 'id': 'support', 'label': 'Support'},
    
    { 'icon': '', 'id': 'proj', 'label': 'PROJECTS'}, 
    { 'icon': '🗡️', 'id': 'proj/UE5', 'label': 'UE5'}, 
    #{ 'icon': '🗡️', 'id': 'proj/UE5/sanct', 'label': 'Sanct'}, 
    #{ 'icon': '🖋️', 'id': 'proj/worldbuild', 'label': 'Worldbuild'}, 
    { 'icon': '🖋️', 'id': 'proj/worldbuild/alrona', 'label': 'Alrona'}, 

    { 'icon': '🖥️', 'id': 'proj/dev', 'label': 'Dev'}, 
    { 'icon': '🕵', 'id': 'proj/dev/ai', 'label': 'AI'}, 
    { 'icon': '👩🏻‍🎓', 'id': 'proj/dev/lifepim', 'label': 'LifePIM'}, 
    #{ 'icon': '📻', 'id': 'proj/elec', 'label': 'Electronics'},             
    { 'icon': '📻', 'id': 'proj/elec/rasbpi', 'label': 'RasbPI'},             

    
]


TABS = [  #Tabs across top of LifePIM
    { 'icon': '🏠', 'id': 'home', 'label': 'Overview', 'desc': 'Overview Dashboard'},
    { 'icon': '🕐', 'id': 'calendar', 'label': 'Cal', 'desc': 'Calendar, Appointments, Events, Reminders (WHEN)'},
    { 'icon': '🏆', 'id': 'goals', 'label': 'Goals', 'desc': 'Goals and Achievements (WHY)'},
    { 'icon': '📝', 'id': 'tasks', 'label': 'Tasks', 'desc': 'Tasks (actual list of things to do)'},
    { 'icon': '📘', 'id': 'how', 'label': 'How', 'desc': 'Blueprints, Task Templates, Processes, Jobs (HOW)'},
    { 'icon': '📔', 'id': 'notes', 'label': 'Notes', 'desc': 'Notes'},
    { 'icon': '📅', 'id': 'data', 'label': 'Data', 'desc': 'Data' },
    { 'icon': '📂', 'id': 'files', 'label': 'Files', 'desc': 'Files'},
    { 'icon': '🖼️', 'id': 'media', 'label': 'Media', 'desc': 'Images / Videos / 2D things'},
    { 'icon': '🎵', 'id': 'audio', 'label': 'Audio', 'desc': 'Music / Podcasts / Sound Effects'},
    { 'icon': '🧱', 'id': '3d', 'label': '3D',  'desc': 'Objects / 3D / Things'},
    { 'icon': '💲', 'id': 'money', 'label': 'Money', 'desc': 'Money'},
    { 'icon': '👤', 'id': 'contacts', 'label': 'People', 'desc': 'Contacts (WHO)'},
    { 'icon': '🌏', 'id': 'places', 'label': 'Places', 'desc': 'Places (WHERE - real life, URL or virt location)'},
    
    #{ 'icon': '📰', 'id': 'news', 'label': 'News', 'desc': 'News, reddit, twitter, RSS feeds'},
    #{ 'icon': '📩', 'id': 'comms', 'label': 'Comms', 'desc' : 'Mail, Chat, Social, Messages  📱📲'},
    #{ 'icon': '💿', 'id': 'media', 'label': 'Media', 'desc': 'Images, Audio, Video'},
    { 'icon': '🎮', 'id': 'apps', 'label': 'Apps', 'desc': 'Apps'},
    #{ 'icon': '💻', 'id': 'etl', 'label': 'ETL', 'desc': 'ETL'},
    # { 'icon': '📜', 'id': 'logs', 'label': 'Logs', 'desc': 'Journal / Logs'},
    #{ 'icon': '⚙', 'id': 'admin', 'label': 'Admin', 'desc': 'Admin'},
    { 'icon': '🤖', 'id': 'agent', 'label': 'Agent', 'desc': 'Agent'},
]


sub_menus = [
    {'root':'notes', 'name':'Add Note', 'fn':'fn_notes_add'},
    {'root':'notes', 'name':'List All', 'fn':'fn_notes_list'},

    {'root':'notes', 'name':'Meeting Notes', 'fn':'fn_notes_meeting'},
    {'root':'notes', 'name':'Project Info', 'fn':'fn_notes_proj'},
    

    {'root':'tasks', 'name':'Add Task', 'fn':'fn_tasks_add'},
    {'root':'tasks', 'name':'List All', 'fn':'fn_tasks_list'},
    {'root':'tasks', 'name':'Today', 'fn':'fn_tasks_today'},
    {'root':'tasks', 'name':'This Week', 'fn':'fn_tasks_week'},
    {'root':'tasks', 'name':'This Month', 'fn':'fn_tasks_month'},
    {'root':'tasks', 'name':'Completed', 'fn':'fn_tasks_done'},


    {'root':'calendar', 'name':'Add Event', 'fn':'fn_calendar_add'},
    {'root':'calendar', 'name':'List All', 'fn':'fn_calendar_list'},
    {'root':'calendar', 'name':'Today', 'fn':'fn_calendar_today'},
    {'root':'calendar', 'name':'Week View', 'fn':'fn_calendar_week'},
    {'root':'calendar', 'name':'Month View', 'fn':'fn_calendar_month'},
    {'root':'calendar', 'name':'Year View', 'fn':'fn_calendar_year'},
    

    {'root':'data', 'name':'Add Table', 'fn':'fn_data_add'},
    {'root':'data', 'name':'List All', 'fn':'fn_data_list'},
    {'root':'data', 'name':'Databases', 'fn':'fn_data_tbl'},
    {'root':'data', 'name':'Spreadsheets', 'fn':'fn_data_csv'},
 
    {'root':'files', 'name':'Favorites', 'fn':'fn_files_fav'},
    {'root':'files', 'name':'Folders', 'fn':'fn_files_folders'},
    {'root':'files', 'name':'Files', 'fn':'fn_files_all'},
    

    {'root':'media', 'name':'Photos', 'fn':'fn_media_photos'},
    {'root':'media', 'name':'Screenshots', 'fn':'fn_media_screenshots'},
    {'root':'media', 'name':'Drawings', 'fn':'fn_media_drawings'},
    {'root':'media', 'name':'Movies', 'fn':'fn_media_movies'},
    {'root':'media', 'name':'Recordings', 'fn':'fn_media_recordings'},    
    

    {'root':'audio', 'name':'Songs', 'fn':'fn_audio_songs'},
    {'root':'audio', 'name':'Albums', 'fn':'fn_audio_albums'},
    {'root':'audio', 'name':'Playlists', 'fn':'fn_audio_playlists'},

]

filters = [
    ['notes', 'type', ['Idea', 'Meeting Note', 'Project Info', 'Research']],
    ['tasks', 'status', ['Not Started', 'In Progress', 'Completed', 'Deferred', 'Waiting on someone else']],
    ['tasks', 'priority', ['Low', 'Medium', 'High', 'Urgent']],
    ['calendar', 'type', ['Appointment', 'Event', 'Reminder', 'Logs']],
    ['calendar', 'view', ['Life', 'Year', 'Quarter', 'Month', 'Fortnight', 'Week', 'Day']],
    ['data', 'type', ['Database', 'Spreadsheet', 'Checklist']],
    ['files', 'type', ['Document', 'PDF', 'Presentation']],
    ['files', 'year', ['1980-1989','1990-1999','2000-2009','2010-2019','2020-2029']],
    ['images', 'type', ['Photo', 'Screenshot', 'Drawing']],
    ['images', 'year', ['1980-1989','1990-1999','2000-2009','2010-2019','2020-2029']],
    ['music', 'type', ['Song', 'Album', 'Playlist']],
    ['music', 'genre', ['Rock', 'Techno', 'Classidal', 'Jazz', 'Pop', 'Folk', 'Other']],
    ['music', 'year', ['1980-1989','1990-1999','2000-2009','2010-2019','2020-2029']],
    ['video', 'type', ['Movie', 'Clip', 'Recording']], 
    ['video', 'year', ['1980-1989','1990-1999','2000-2009','2010-2019','2020-2029']],
]   


project_specific_tables = [
    'car_service_records',
    'car_fuel_logs',
    'health_medical_info',
    'home_utilities',
    'home_repairs',
    'games_collection',
    'work_meetings',
    'shopping_receipts',
    'family_birthdays',
    'food_recipes',
    'admin_warranties',
    'pers_journal',
    'study_courses',
    'design_inspiration',
    'fun_hobbies',
    'web_bookmarks',    
    'business_invoices',
    'dev_bugs',
    'rasbpi_projects',
    'support_warranties',
    'ai_projects',
]



api_routes = [
    '/',
    '/notes',
    '/notes/<id>',
    '/tasks',
    '/tasks/<id>',
    '/calendar',
    '/calendar/<id>',
    '/files',
    '/files/<filename>',
    '/options',
]


current_index_list = [
    r'\\FANGORN\user\duncan\LifePIM\Data',
    r'\\FANGORN\user\duncan\C\user\docs',
    r'\\FANGORN\user\duncan\C\user\dev',
    r'\\FANGORN\user\duncan\C\user\AIKIF',
    r'\\FANGORN\user\duncan\C\user\acute',
    r'\\FANGORN\user\DATA\photos',
    r'\\FANGORN\user\DATA\eBooks',
    r'\\FANGORN\user\DATA\3D',
    r'\\FANGORN\photo',
    r'\\FANGORN\music',
    r'D:\docs\Unreal Projects',
    r'D:\dev\src',
]


port_num=9741           # port to browse to, eg. http://127.0.0.1:9741/
WEB_VERSION = "DEV"     # to show debug lines in web server
base_url = 'https://www.lifepim.com'    # testing, point to live site for API
base_url = '127.0.0.1:5000'             # running local (default)


# --------------------------------------------------------
# Functions


def get_conn_str():
	conn_str = {}
	with open(logon_file, 'r') as f:
		conn_str['host'] = f.readline().strip(' ').strip('\n')
		conn_str['user'] = f.readline().strip(' ').strip('\n')
		conn_str['pass'] = f.readline().strip(' ').strip('\n')
		conn_str['db'] = f.readline().strip(' ').strip('\n')

	return conn_str
