#!/usr/bin/python3
# coding: utf-8
# config.py


import copy
import json
import os
import sqlite3
import sys
import types

# ----------------------------------------------------------------------------
# Folder Locations
# 

APP_VERSION = "3.1.004"


#user_folder = r'\\FANGORN\user\duncan\LifePIM_Data'
user_folder = r"D:\DATA_LLM\SAMPLE_DATA\lifepim_desktop_data"

logon_file = os.path.join(user_folder, 'configuration', 'lifepim.par')
data_folder = os.path.join(user_folder, 'DATA')
index_folder = os.path.join(user_folder, 'index')
calendar_folder = os.path.join(user_folder, 'calendar')
folder_list_file =  os.path.join(user_folder, 'configuration', 'folders.lis')
export_data_folder_base = os.path.join(user_folder, 'export_data')
LAN_USER_ROOT_BASE = os.getenv(
    "LIFEPIM_LAN_USER_ROOT_BASE",
    r"N:\duncan\LifePIM_Data\DATA\lan_users",
)
etl_folders_csv = r"E:\BK_fangorn\user\duncan\LifePIM_Data\configuration\all_folders.csv"
area_mappings_csv = os.getenv(
    "LIFEPIM_AREA_MAPPINGS_CSV",
    r"E:\BK_fangorn\user\duncan\LifePIM_Data\configuration\area_folders.csv",
)
FILELIST_DB = r"D:\TRANSFER_NAS\filelister\filelist_master.db"
FILE_INVENTORY_DB = os.path.join(user_folder, "files.db")
FILELIST_IMAGE_WHERE = r"WHERE folder_name IN ('Photos', 'Movies', 'TV Shows')"
FILELIST_AUDIO_WHERE = r"WHERE folder_name = 'Music'"
PATH_ALIASES = [
    (r"N:\duncan", r"E:\BK_fangorn\user\duncan"),
    (r"N:\\", r"E:\BK_fangorn\user"),
]


#db_name = os.path.join(user_folder, 'DATA', 'SQL', 'lifepim.db')
db_name = os.path.join(user_folder, 'lifepim.db')

DB_FILE = db_name
if os.getenv("LIFEPIM_DEBUG_CONFIG"):
    print('DB_FILE = ' + DB_FILE)

# ----------------------------------------------------------------------------
# Table Definitions
#
# Note - all tables have columns specified below as well as standard metadata
# columns : 
#   id  = unique id of record, autogenerated - should be in column position 1
#   user_name   = TEXT username of person adding record, default to logged on user - 2nd to last column in table
#   rec_extract_date text = DATETIME record updated or inserted - last column in table
#
#  The DATA TYPE of all columns should be TEXT unless the name of the column changes it below
#  column name contains 'date' = DATETIME
#  column name contains 'amount', 'total', 'num_' = NUMBER
#  
table_def = [
	{'name':'lp_notes', 'route':'notes', 'display_name':'Notes', 'col_list':['file_name','path', 'folder_id', 'size', 'title', 'color', 'date_created', 'date_modified', 'area', 'important', 'source_note_id']},
	{'name':'lp_tasks', 'route':'tasks', 'display_name':'Tasks', 'col_list':['title','content', 'area', 'start_date', 'due_date', 'status', 'task_kind', 'app_action_id', 'parameters_json', 'completed_date']},
	{'name':'lp_calendar_events', 'route':'calendar', 'display_name':'Events', 'col_list':['title','content', 'event_date', 'remind_date', 'area']},
	{'name':'lp_media', 'route':'media', 'display_name':'Media', 'col_list':['path', 'filename', 'ext', 'media_type', 'size_bytes', 'mtime_utc', 'ctime_utc', 'hash']},
	{'name':'lp_audio', 'route':'audio', 'display_name':'Audio', 'col_list':['file_name','path', 'folder_id', 'file_type', 'size', 'date_modified', 'duration', 'artist', 'album', 'song', 'area']},
	{'name':'lp_3d', 'route':'3d', 'display_name':'3D', 'col_list':['file_name','path', 'folder_id', 'size', 'date_modified', 'area']},
	{'name':'lp_app', 'route':'apps', 'display_name':'Apps', 'col_list':['title', 'kind', 'description', 'icon', 'favorite', 'enabled', 'path', 'repository_url', 'website_url', 'language', 'version', 'tags', 'comments', 'last_used_date', 'usage_count']},

	{'name':'lp_goals', 'route':'goals', 'display_name':'Goals', 'col_list':['parent_goal_id', 'title','description', 'goal_date', 'remind_date', 'area']},
	{'name':'lp_how', 'route':'how', 'display_name':'How', 'col_list':['parent_how_id', 'title','description', 'area']},
	{'name':'lp_data', 'route':'data', 'display_name':'Data', 'col_list':['name','description', 'tbl_name', 'col_list', 'area']},
	{'name':'lp_files', 'route':'files', 'display_name':'Files', 'col_list':['filelist_name','path', 'folder_id', 'file_type', 'area']},
	{'name':'lp_places', 'route':'places', 'display_name':'Places', 'col_list':['name','desc', 'address_street', 'suburb', 'postcode', 'state', 'country', 'gps_lat', 'gps_long']},

]

"""
use the route value in config.py > table_def to decide which table the top tab uses
from the table name, also lookup the col_list to determine the select statement
Implement the tasks view, add, edit and delete using these parameters to directly
call the data.py > get_data, add_record, update_record, delete_record.
There should not be separate get_tasks, add_tasks in the data.py
"""

# ----------------------------------------------------------------------------
# Interface configuration

MONEY_FREQUENCIES = ["weekly", "fortnightly", "monthly", "quarterly", "yearly", "once"]
MONEY_ASSET_TYPES = ["house", "shares", "super", "car", "bank", "other"]
MONEY_LOAN_TYPES = ["home loan 1", "home loan 2", "credit card", "student loan", "other"]
MONEY_INCOME_TYPES = ["wages", "dividends", "rent", "business", "royalties", "other"]
MONEY_BILL_TYPES = ["loan repayments", "electricity", "phone", "insurance", "rates", "internet", "other"]
MONEY_PLAN_STATUSES = ["idea", "planned", "bought", "cancelled"]
MONEY_SHARE_MARKETS = [
    "Australia (ASX)",
    "United States (US)",
    "United Kingdom (LSE)",
    "Canada (TSX)",
    "India (NSE)",
    "Manual / Yahoo symbol",
]

MONEY_SECTIONS = [
    {
        "id": "assets",
        "label": "Assets",
        "table": "lp_money_assets",
        "pk": "asset_id",
        "default_sort": "asset_type ASC, name ASC",
        "summary": "sum:current_value",
        "columns": [
            {"name": "asset_type", "label": "Type", "type": "select", "options": MONEY_ASSET_TYPES, "required": True},
            {"name": "name", "label": "Name", "type": "text", "required": True},
            {"name": "institution", "label": "Institution / Location", "type": "text"},
            {"name": "current_value", "label": "Current Value", "type": "money"},
            {"name": "purchase_value", "label": "Purchase Value", "type": "money"},
            {"name": "valuation_date", "label": "Valuation Date", "type": "date"},
            {"name": "notes", "label": "Notes", "type": "textarea"},
        ],
    },
    {
        "id": "loans",
        "label": "Loans",
        "table": "lp_money_loans",
        "pk": "loan_id",
        "default_sort": "loan_type ASC, lender ASC",
        "summary": "sum:balance",
        "columns": [
            {"name": "loan_type", "label": "Type", "type": "select", "options": MONEY_LOAN_TYPES, "required": True},
            {"name": "lender", "label": "Lender", "type": "text", "required": True},
            {"name": "balance", "label": "Balance", "type": "money"},
            {"name": "interest_rate", "label": "Interest Rate %", "type": "number"},
            {"name": "repayment_amount", "label": "Repayment", "type": "money"},
            {"name": "repayment_frequency", "label": "Frequency", "type": "select", "options": MONEY_FREQUENCIES, "default": "monthly"},
            {"name": "next_payment_date", "label": "Next Payment", "type": "date"},
            {"name": "notes", "label": "Notes", "type": "textarea"},
        ],
    },
    {
        "id": "income",
        "label": "Income",
        "table": "lp_money_income",
        "pk": "income_id",
        "default_sort": "income_type ASC, source ASC",
        "summary": "annualized:amount:frequency",
        "columns": [
            {"name": "income_type", "label": "Type", "type": "select", "options": MONEY_INCOME_TYPES, "required": True},
            {"name": "source", "label": "Source", "type": "text", "required": True},
            {"name": "amount", "label": "Amount", "type": "money"},
            {"name": "frequency", "label": "Frequency", "type": "select", "options": MONEY_FREQUENCIES, "default": "monthly"},
            {"name": "next_date", "label": "Next Date", "type": "date"},
            {"name": "taxable", "label": "Taxable", "type": "checkbox", "default": 1},
            {"name": "notes", "label": "Notes", "type": "textarea"},
        ],
    },
    {
        "id": "bills",
        "label": "Bills",
        "table": "lp_money_bills",
        "pk": "bill_id",
        "default_sort": "due_date ASC, supplier ASC",
        "summary": "annualized:amount:frequency",
        "columns": [
            {"name": "bill_type", "label": "Type", "type": "select", "options": MONEY_BILL_TYPES, "required": True},
            {"name": "supplier", "label": "Supplier", "type": "text", "required": True},
            {"name": "amount", "label": "Amount", "type": "money"},
            {"name": "frequency", "label": "Frequency", "type": "select", "options": MONEY_FREQUENCIES, "default": "monthly"},
            {"name": "due_date", "label": "Due Date", "type": "date"},
            {"name": "autopay", "label": "Autopay", "type": "checkbox"},
            {"name": "notes", "label": "Notes", "type": "textarea"},
        ],
    },
    {
        "id": "tax",
        "label": "Tax Deductions",
        "table": "lp_money_tax_deductions",
        "pk": "deduction_id",
        "default_sort": "purchase_date DESC, supplier ASC",
        "summary": "sum:amount",
        "columns": [
            {"name": "purchase_date", "label": "Date", "type": "date", "required": True},
            {"name": "supplier", "label": "Supplier", "type": "text", "required": True},
            {"name": "item", "label": "Item", "type": "text", "required": True},
            {"name": "amount", "label": "Amount", "type": "money"},
            {"name": "reason", "label": "Reason", "type": "textarea", "required": True},
            {"name": "tax_year", "label": "Tax Year", "type": "text"},
            {"name": "receipt_path", "label": "Receipt Path", "type": "text"},
        ],
    },
    {
        "id": "planned",
        "label": "Planned",
        "table": "lp_money_plans",
        "pk": "plan_id",
        "default_sort": "(target_date IS NULL) ASC, target_date ASC, priority ASC",
        "summary": "sum:estimated_cost",
        "columns": [
            {"name": "item", "label": "Item", "type": "text", "required": True},
            {"name": "domain", "label": "Reason / Domain", "type": "text", "default": "General"},
            {"name": "estimated_cost", "label": "Estimated Cost", "type": "money"},
            {"name": "target_date", "label": "Target Date", "type": "date"},
            {"name": "priority", "label": "Priority", "type": "number", "default": 3},
            {"name": "status", "label": "Status", "type": "select", "options": MONEY_PLAN_STATUSES, "default": "planned"},
            {"name": "notes", "label": "Notes", "type": "textarea"},
        ],
    },
    {
        "id": "watchlist",
        "label": "Share Watchlist",
        "table": "lp_money_share_watchlist",
        "pk": "watch_id",
        "default_sort": "symbol ASC",
        "summary": "count",
        "columns": [
            {"name": "symbol", "label": "Symbol", "type": "text", "required": True},
            {"name": "market", "label": "Market", "type": "select", "options": MONEY_SHARE_MARKETS, "default": "Australia (ASX)"},
            {"name": "company_name", "label": "Company", "type": "text"},
            {"name": "target_price", "label": "Target Price", "type": "money"},
            {"name": "current_price", "label": "Delayed Price", "type": "money", "readonly": True},
            {"name": "price_updated_at", "label": "Price Updated", "type": "text", "readonly": True},
            {"name": "notes", "label": "Notes", "type": "textarea"},
        ],
    },
    {
        "id": "pretend",
        "label": "Pretend Purchases",
        "table": "lp_money_share_trades",
        "pk": "trade_id",
        "default_sort": "trade_date DESC, symbol ASC",
        "summary": "sum:profit_loss",
        "derived_columns": [{"name": "profit_loss", "label": "P/L", "type": "money"}],
        "columns": [
            {"name": "symbol", "label": "Symbol", "type": "text", "required": True},
            {"name": "market", "label": "Market", "type": "select", "options": MONEY_SHARE_MARKETS, "default": "Australia (ASX)"},
            {"name": "trade_date", "label": "Pretend Buy Date", "type": "date"},
            {"name": "quantity", "label": "Quantity", "type": "number"},
            {"name": "pretend_buy_price", "label": "Buy Price", "type": "money"},
            {"name": "current_price", "label": "Delayed Price", "type": "money", "readonly": True},
            {"name": "fees", "label": "Fees", "type": "money"},
            {"name": "price_updated_at", "label": "Price Updated", "type": "text", "readonly": True},
            {"name": "notes", "label": "Notes", "type": "textarea"},
        ],
    },
]

MONEY_QUOTE_PROVIDER = "yahoo_chart"
MONEY_QUOTE_DELAY_MINUTES = 15

# Pagination
RECS_PER_PAGE = 200
IMAGES_PER_PAGE = 50

# Search result snippet length for content matches
SEARCH_CONTENT_SNIPPET_LEN = 400

# Audio player settings
AUDIO_SHOW_FREQ_BAR = "Y"

# Places map settings
PLACES_MAP_EXTERNAL_URLS = [
    {
        "label": "Google Maps",
        "url": "https://www.google.com/maps/search/?api=1&query={lat},{lon}",
    },
    {
        "label": "Street View",
        "url": "https://www.google.com/maps/@?api=1&map_action=pano&viewpoint={lat},{lon}",
    },
    {
        "label": "OpenStreetMap",
        "url": "https://www.openstreetmap.org/?mlat={lat}&mlon={lon}#map=18/{lat}/{lon}",
    },
]

# Development server settings
APP_AUTO_RELOAD = True

# Area list default
area_list = ['Dev','Design','Fun','Games','Family','Car',
             'Business','Web','Home','Study','Health','Work',
             'RasbPI','AI','Support','Pers']


SIDE_TABS_GROUPS = [  # for possible sub folders
    { 'icon': '*', 'id': 'All', 'sub_list': 'All Areas'},
    { 'icon': '🔒', 'id': 'PERS', 'sub_list': 'Pers,Health,Home,Car,Family,Food'},
    { 'icon': '🎉', 'id': 'FUN', 'sub_list': 'games, travel, Music, movies, Books, Hobbies'},
    { 'icon': '💼', 'id': 'WORK', 'sub_list': 'Work,Business,Side Gigs,Commision'},
    { 'icon': '🛠️', 'id': 'MAKE', 'sub_list': 'Dev,Design,Web,RasbPI,AI,PC Support'},
    { 'icon': '👩🏻‍🎓', 'id': 'LEARN', 'sub_list': 'Study, Skills, Languages, Courses'},
]

SIDE_TABS = [  # Tabs down left side of LifePIM - any area goes into one of these groups
    { 'icon': '*', 'id': 'All', 'label': 'All Areas'},
    { 'icon': '❓', 'id': 'unmapped', 'label': 'Unmapped'},
    { 'icon': '', 'id': 'spacer', 'label': 'PERS'}, 

    #{ 'icon': '🔒', 'id': 'pers', 'label': 'Personal'},
    { 'icon': '💊', 'id': 'pers/health', 'label': 'Health'}, 
    { 'icon': '👪', 'id': 'family', 'label': 'Family'}, 
    { 'icon': '🏚️', 'id': 'house', 'label': 'House'}, 
    { 'icon': '🌴', 'id': 'garden', 'label': 'Garden'}, 
    { 'icon': '🚗', 'id': 'car', 'label': 'Car'}, 

    { 'icon': '', 'id': 'fun', 'label': 'FUN'}, 

    { 'icon': '🎉', 'id': 'fun/events', 'label': 'Events'},  # note that top tabs separate movies,
    { 'icon': '🕹️', 'id': 'fun/games', 'label': 'Games'}, 
    { 'icon': '🍕', 'id': 'fun/food', 'label': 'Food'}, 

    { 'icon': '🏈', 'id': 'fun/sport', 'label': 'Sport'}, 
    { 'icon': '👣', 'id': 'fun/travel', 'label': 'Travel'}, 



    { 'icon': '', 'id': 'make', 'label': 'MAKE'}, 


    #{ 'icon': '🖥️', 'id': 'dev/Python', 'label': 'Python'}, 
    { 'icon': '📐', 'id': 'make/design', 'label': 'Design'},   # can be Art / Draw
    { 'icon': '🖋️', 'id': 'make/write', 'label': 'Writing'}, 
    #{ 'icon': '📐', 'id': 'design/programs', 'label': 'Program Design'}, 
    { 'icon': '🛠️', 'id': 'make/build', 'label': 'Build'}, 
    
    #{ 'icon': '📻', 'id': 'make/pc', 'label': 'PC'}, 

    { 'icon': '', 'id': 'work', 'label': 'WORK'}, 


    { 'icon': '💼', 'id': 'work/job', 'label': 'Job'}, 
    { 'icon': '💼', 'id': 'work/business', 'label': 'Business'}, 
    #{ 'icon': '💼', 'id': 'work/freelance', 'label': 'Freelance'}, 

    { 'icon': '👩🏻‍🎓', 'id': 'work/study', 'label': 'Study'}, 
    
    #{ 'icon': '🧰', 'id': 'support', 'label': 'Support'},
    
    { 'icon': '', 'id': 'area', 'label': 'AREAS'}, 
    { 'icon': '🗡️', 'id': 'area/UE5', 'label': 'UE5'}, 
    #{ 'icon': '🗡️', 'id': 'area/UE5/sanct', 'label': 'Sanct'}, 
    #{ 'icon': '🖋️', 'id': 'area/worldbuild', 'label': 'Worldbuild'}, 
    { 'icon': '🖋️', 'id': 'area/worldbuild/alrona', 'label': 'Alrona'}, 

    { 'icon': '🖥️', 'id': 'area/dev', 'label': 'Dev'}, 
    { 'icon': '🕵', 'id': 'area/dev/ai', 'label': 'AI'}, 
    { 'icon': '👩🏻‍🎓', 'id': 'area/dev/lifepim', 'label': 'LifePIM'}, 
    #{ 'icon': '📻', 'id': 'area/elec', 'label': 'Electronics'},             
    { 'icon': '📻', 'id': 'area/elec/rasbpi', 'label': 'RasbPI'},             

    
]


TABS = [  #Tabs across top of LifePIM
    { 'icon': '🏠', 'id': 'home', 'label': 'Overview', 'desc': 'Overview Dashboard'},
    { 'icon': '🕐', 'id': 'calendar', 'label': 'Cal', 'desc': 'Calendar, Appointments, Events, Reminders (WHEN)'},
    { 'icon': '🏆', 'id': 'goals', 'label': 'Goals', 'desc': 'Goals and Achievements (WHY)'},
    { 'icon': '📝', 'id': 'tasks', 'label': 'Tasks', 'desc': 'Tasks (actual list of things to do)'},
    { 'icon': '📘', 'id': 'how', 'label': 'How', 'desc': 'Blueprints, Task Templates, Processes, Jobs (HOW)'},
    { 'icon': '📔', 'id': 'notes', 'label': 'Notes', 'desc': 'Notes'},
    { 'icon': '📅', 'id': 'data', 'label': 'Data', 'desc': 'Data' },
    { 'icon': '📂', 'id': 'files', 'label': 'Files', 'desc': 'Files'},
    { 'icon': '🖼️', 'id': 'media', 'label': 'Media', 'desc': 'Images / Videos / 2D things'},
    { 'icon': '🎵', 'id': 'audio', 'label': 'Audio', 'desc': 'Music / Podcasts / Sound Effects'},
    { 'icon': '🧱', 'id': '3d', 'label': '3D',  'desc': 'Objects / 3D / Things'},
    { 'icon': '💲', 'id': 'money', 'label': 'Money', 'desc': 'Money'},
    { 'icon': '👤', 'id': 'contacts', 'label': 'People', 'desc': 'Contacts (WHO)'},
    { 'icon': '🌏', 'id': 'places', 'label': 'Places', 'desc': 'Places (WHERE - real life, URL or virt location)'},
    
    #{ 'icon': '📰', 'id': 'news', 'label': 'News', 'desc': 'News, reddit, twitter, RSS feeds'},
    #{ 'icon': '📩', 'id': 'comms', 'label': 'Comms', 'desc' : 'Mail, Chat, Social, Messages  📱📲'},
    #{ 'icon': '💿', 'id': 'media', 'label': 'Media', 'desc': 'Images, Audio, Video'},
    { 'icon': '🎮', 'id': 'apps', 'label': 'Apps', 'desc': 'Apps'},
    #{ 'icon': '💻', 'id': 'etl', 'label': 'ETL', 'desc': 'ETL'},
    # { 'icon': '📜', 'id': 'logs', 'label': 'Logs', 'desc': 'Journal / Logs'},
    { 'icon': '⚙', 'id': 'admin', 'label': 'Admin', 'desc': 'Admin'},
    { 'icon': '🤖', 'id': 'agent', 'label': 'Agent', 'desc': 'Agent'},
]


sub_menus = [
    {'root':'notes', 'name':'Add Note', 'fn':'fn_notes_add'},
    {'root':'notes', 'name':'List All', 'fn':'fn_notes_list'},

    {'root':'notes', 'name':'Meeting Notes', 'fn':'fn_notes_meeting'},
    {'root':'notes', 'name':'Area Info', 'fn':'fn_notes_area'},
    

    {'root':'tasks', 'name':'Add Task', 'fn':'fn_tasks_add'},
    {'root':'tasks', 'name':'List All', 'fn':'fn_tasks_list'},
    {'root':'tasks', 'name':'Today', 'fn':'fn_tasks_today'},
    {'root':'tasks', 'name':'This Week', 'fn':'fn_tasks_week'},
    {'root':'tasks', 'name':'This Month', 'fn':'fn_tasks_month'},
    {'root':'tasks', 'name':'Completed', 'fn':'fn_tasks_done'},


    {'root':'calendar', 'name':'Add Event', 'fn':'fn_calendar_add'},
    {'root':'calendar', 'name':'List All', 'fn':'fn_calendar_list'},
    {'root':'calendar', 'name':'Today', 'fn':'fn_calendar_today'},
    {'root':'calendar', 'name':'Week View', 'fn':'fn_calendar_week'},
    {'root':'calendar', 'name':'Month View', 'fn':'fn_calendar_month'},
    {'root':'calendar', 'name':'Year View', 'fn':'fn_calendar_year'},
    

    {'root':'data', 'name':'Add Table', 'fn':'fn_data_add'},
    {'root':'data', 'name':'List All', 'fn':'fn_data_list'},
    {'root':'data', 'name':'Databases', 'fn':'fn_data_tbl'},
    {'root':'data', 'name':'Spreadsheets', 'fn':'fn_data_csv'},
 
    {'root':'files', 'name':'Favorites', 'fn':'fn_files_fav'},
    {'root':'files', 'name':'Folders', 'fn':'fn_files_folders'},
    {'root':'files', 'name':'Files', 'fn':'fn_files_all'},
    

    {'root':'media', 'name':'Photos', 'fn':'fn_media_photos'},
    {'root':'media', 'name':'Screenshots', 'fn':'fn_media_screenshots'},
    {'root':'media', 'name':'Drawings', 'fn':'fn_media_drawings'},
    {'root':'media', 'name':'Movies', 'fn':'fn_media_movies'},
    {'root':'media', 'name':'Recordings', 'fn':'fn_media_recordings'},    
    

    {'root':'audio', 'name':'Songs', 'fn':'fn_audio_songs'},
    {'root':'audio', 'name':'Albums', 'fn':'fn_audio_albums'},
    {'root':'audio', 'name':'Playlists', 'fn':'fn_audio_playlists'},

]

filters = [
    ['notes', 'type', ['Idea', 'Meeting Note', 'Area Info', 'Research']],
    ['tasks', 'status', ['Not Started', 'In Progress', 'Completed', 'Deferred', 'Waiting on someone else']],
    ['tasks', 'priority', ['Low', 'Medium', 'High', 'Urgent']],
    ['calendar', 'type', ['Appointment', 'Event', 'Reminder', 'Logs']],
    ['calendar', 'view', ['Life', 'Year', 'Quarter', 'Month', 'Fortnight', 'Week', 'Day']],
    ['data', 'type', ['Database', 'Spreadsheet', 'Checklist']],
    ['files', 'type', ['Document', 'PDF', 'Presentation']],
    ['files', 'year', ['1980-1989','1990-1999','2000-2009','2010-2019','2020-2029']],
    ['images', 'type', ['Photo', 'Screenshot', 'Drawing']],
    ['images', 'year', ['1980-1989','1990-1999','2000-2009','2010-2019','2020-2029']],
    ['music', 'type', ['Song', 'Album', 'Playlist']],
    ['music', 'genre', ['Rock', 'Techno', 'Classidal', 'Jazz', 'Pop', 'Folk', 'Other']],
    ['music', 'year', ['1980-1989','1990-1999','2000-2009','2010-2019','2020-2029']],
    ['video', 'type', ['Movie', 'Clip', 'Recording']], 
    ['video', 'year', ['1980-1989','1990-1999','2000-2009','2010-2019','2020-2029']],
]   


area_specific_tables = [
    'car_service_records',
    'car_fuel_logs',
    'health_medical_info',
    'home_utilities',
    'home_repairs',
    'games_collection',
    'work_meetings',
    'shopping_receipts',
    'family_birthdays',
    'food_recipes',
    'admin_warranties',
    'pers_journal',
    'study_courses',
    'design_inspiration',
    'fun_hobbies',
    'web_bookmarks',    
    'business_invoices',
    'dev_bugs',
    'rasbpi_areas',
    'support_warranties',
    'ai_areas',
]



api_routes = [
    '/',
    '/notes',
    '/notes/<id>',
    '/tasks',
    '/tasks/<id>',
    '/calendar',
    '/calendar/<id>',
    '/files',
    '/files/<filename>',
    '/options',
]


current_index_list = [
    r'\\FANGORN\user\duncan\LifePIM\Data',
    r'\\FANGORN\user\duncan\C\user\docs',
    r'\\FANGORN\user\duncan\C\user\dev',
    r'\\FANGORN\user\duncan\C\user\AIKIF',
    r'\\FANGORN\user\duncan\C\user\acute',
    r'\\FANGORN\user\DATA\photos',
    r'\\FANGORN\user\DATA\eBooks',
    r'\\FANGORN\user\DATA\3D',
    r'\\FANGORN\photo',
    r'\\FANGORN\music',
    r'D:\docs\Unreal Projects',
    r'D:\dev\src',
]


port_num=9741           # port to browse to, eg. http://127.0.0.1:9741/
WEB_VERSION = "DEV"     # to show debug lines in web server
base_url = 'https://www.lifepim.com'    # testing, point to live site for API
base_url = '127.0.0.1'             # running local (default)

# ----------------------------------------------------------------------------
# Calendar view configuration
CAL_TIMESLOT_START_TIME = 800   # 0800
CAL_TIMESLOT_END_TIME = 2330    # 2330
CAL_TIMESLOT_MINUTES = 30
CAL_HIGHLIGHT_DAY_DATA = 'Bold'
CAL_HIGHLIGHT_DAY_TODAY = 'Red'
CAL_COL_BG_DAY = 'white'
CAL_COL_BG_WEEKEND = '#f0f0f0'
CAL_COL_BG_TODAY = 'yellow'
CAL_TIME_START_WORK = 900   # 0900
CAL_TIME_END_WORK = 1700    # 1700
CAL_TIME_LUNCH_START = 1200 # 1200
CAL_TIME_LUNCH_END = 1230   # 1230
NOTE_CARD_DEF_BG_COL = '#f0f0f0'
OVERVIEW_GRID_W = '100%'
OVERVIEW_GRID_H = '600px'


# --------------------------------------------------------
# Functions


def get_conn_str():
	conn_str = {}
	with open(get_config_value('logon_file'), 'r') as f:
		conn_str['host'] = f.readline().strip(' ').strip('\n')
		conn_str['user'] = f.readline().strip(' ').strip('\n')
		conn_str['pass'] = f.readline().strip(' ').strip('\n')
		conn_str['db'] = f.readline().strip(' ').strip('\n')

	return conn_str


# --------------------------------------------------------
# Runtime settings overrides
#
# Values above are defaults. Saved rows in sys_settings with keys like
# config.RECS_PER_PAGE override those defaults when the app reads this module.

CONFIG_SETTING_PREFIX = "config."
BOOTSTRAP_CONFIG_NAMES = {"DB_FILE", "db_name", "user_folder", "data_folder"}
_CONFIG_DEFAULTS = {}
_CONFIG_OVERRIDE_CACHE = {}
_CONFIG_OVERRIDE_CACHE_LOADED = False
_CONFIG_OVERRIDE_LOADING = False


def _is_config_setting_value(value):
	return isinstance(value, (str, int, float, bool, list, tuple, dict)) or value is None


def _capture_config_defaults():
	excluded = {
		"copy",
		"json",
		"os",
		"sqlite3",
		"sys",
		"types",
		"CONFIG_SETTING_PREFIX",
	}
	return {
		key: copy.deepcopy(value)
		for key, value in globals().items()
		if not key.startswith("_")
		and key not in excluded
		and _is_config_setting_value(value)
	}


def _settings_db_file():
	value = _CONFIG_DEFAULTS.get("DB_FILE") or _CONFIG_DEFAULTS.get("db_name") or "lifepim.db"
	if not os.path.isabs(value):
		value = os.path.abspath(os.path.join(os.path.dirname(__file__), value))
	return value


def _normalize_config_db_file(value):
	if not value:
		return ""
	if not os.path.isabs(value):
		value = os.path.abspath(os.path.join(os.path.dirname(__file__), value))
	return value


def _read_config_overrides(db_file):
	overrides = {}
	db_file = _normalize_config_db_file(db_file)
	if not db_file or not os.path.exists(db_file):
		return overrides
	conn = sqlite3.connect(db_file)
	try:
		rows = conn.execute(
			"SELECT setting_key, setting_value FROM sys_settings WHERE setting_key LIKE ?",
			(CONFIG_SETTING_PREFIX + "%",),
		).fetchall()
	finally:
		conn.close()
	return {
		row[0][len(CONFIG_SETTING_PREFIX):]: row[1]
		for row in rows
		if row[0].startswith(CONFIG_SETTING_PREFIX)
	}


def _db_file_from_overrides(overrides):
	value = overrides.get("DB_FILE") or overrides.get("db_name") or ""
	if not value:
		return ""
	try:
		value = parse_config_value("DB_FILE" if "DB_FILE" in overrides else "db_name", value)
	except Exception:
		pass
	return _normalize_config_db_file(str(value))


def _ensure_override_cache():
	global _CONFIG_OVERRIDE_CACHE_LOADED, _CONFIG_OVERRIDE_LOADING
	if _CONFIG_OVERRIDE_CACHE_LOADED or _CONFIG_OVERRIDE_LOADING:
		return
	_CONFIG_OVERRIDE_LOADING = True
	try:
		bootstrap_db_file = _settings_db_file()
		bootstrap_overrides = _read_config_overrides(bootstrap_db_file)
		_CONFIG_OVERRIDE_CACHE.update(bootstrap_overrides)
		active_db_file = _db_file_from_overrides(bootstrap_overrides)
		if active_db_file and os.path.normcase(active_db_file) != os.path.normcase(_normalize_config_db_file(bootstrap_db_file)):
			_CONFIG_OVERRIDE_CACHE.update(_read_config_overrides(active_db_file))
	except Exception:
		# Config must remain importable before the database/settings schema exists.
		pass
	finally:
		_CONFIG_OVERRIDE_LOADING = False
		_CONFIG_OVERRIDE_CACHE_LOADED = True


def refresh_config_overrides():
	global _CONFIG_OVERRIDE_CACHE_LOADED
	_CONFIG_OVERRIDE_CACHE.clear()
	_CONFIG_OVERRIDE_CACHE_LOADED = False
	_ensure_override_cache()


def _ensure_bootstrap_settings_schema(conn):
	conn.executescript(
		"""
		CREATE TABLE IF NOT EXISTS sys_settings (
			setting_key TEXT PRIMARY KEY,
			setting_value TEXT NOT NULL,
			category TEXT NOT NULL DEFAULT 'General',
			label TEXT NOT NULL DEFAULT '',
			updated_utc TEXT NOT NULL
		);
		"""
	)


def _bootstrap_conn():
	db_file = _settings_db_file()
	os.makedirs(os.path.dirname(db_file), exist_ok=True)
	conn = sqlite3.connect(db_file)
	_ensure_bootstrap_settings_schema(conn)
	return conn


def save_bootstrap_config_override(name, value):
	if name not in BOOTSTRAP_CONFIG_NAMES:
		return
	conn = _bootstrap_conn()
	try:
		conn.execute(
			"INSERT INTO sys_settings (setting_key, setting_value, category, label, updated_utc) "
			"VALUES (?, ?, 'Config', ?, strftime('%Y-%m-%dT%H:%M:%SZ','now')) "
			"ON CONFLICT(setting_key) DO UPDATE SET "
			"setting_value=excluded.setting_value, category=excluded.category, "
			"label=excluded.label, updated_utc=excluded.updated_utc",
			(CONFIG_SETTING_PREFIX + name, str(value), name),
		)
		conn.commit()
	finally:
		conn.close()


def delete_bootstrap_config_override(name):
	if name not in BOOTSTRAP_CONFIG_NAMES:
		return
	db_file = _settings_db_file()
	if not os.path.exists(db_file):
		return
	conn = sqlite3.connect(db_file)
	try:
		_ensure_bootstrap_settings_schema(conn)
		conn.execute("DELETE FROM sys_settings WHERE setting_key = ?", (CONFIG_SETTING_PREFIX + name,))
		conn.commit()
	finally:
		conn.close()


def serialize_config_value(value):
	if isinstance(value, (list, tuple, dict, bool)) or value is None:
		return json.dumps(value, ensure_ascii=True)
	return str(value)


def parse_config_value(name, value):
	default = _CONFIG_DEFAULTS.get(name)
	if isinstance(default, bool):
		return str(value).strip().lower() in {"1", "true", "yes", "on"}
	if isinstance(default, int) and not isinstance(default, bool):
		return int(str(value).strip())
	if isinstance(default, float):
		return float(str(value).strip())
	if isinstance(default, (list, tuple, dict)) or default is None:
		parsed = json.loads(value)
		return tuple(parsed) if isinstance(default, tuple) else parsed
	return str(value)


def deserialize_config_value(name, value):
	try:
		return parse_config_value(name, value)
	except Exception:
		return copy.deepcopy(_CONFIG_DEFAULTS.get(name))


def get_config_value(name):
	if name not in _CONFIG_DEFAULTS:
		return globals().get(name)
	_ensure_override_cache()
	if name in _CONFIG_OVERRIDE_CACHE:
		return deserialize_config_value(name, _CONFIG_OVERRIDE_CACHE[name])
	return copy.deepcopy(_CONFIG_DEFAULTS[name])


def list_config_settings(conn=None):
	saved = {}
	if conn is not None:
		try:
			rows = conn.execute(
				"SELECT setting_key, setting_value, updated_utc FROM sys_settings WHERE setting_key LIKE ?",
				(CONFIG_SETTING_PREFIX + "%",),
			).fetchall()
			for row in rows:
				key = row["setting_key"] if hasattr(row, "keys") else row[0]
				name = key[len(CONFIG_SETTING_PREFIX):]
				saved[name] = {
					"value": row["setting_value"] if hasattr(row, "keys") else row[1],
					"updated_utc": row["updated_utc"] if hasattr(row, "keys") else row[2],
				}
		except Exception:
			saved = {}
	_ensure_override_cache()
	for name, value in _CONFIG_OVERRIDE_CACHE.items():
		if name not in saved:
			saved[name] = {"value": value, "updated_utc": ""}
	return [
		{
			"name": name,
			"key": CONFIG_SETTING_PREFIX + name,
			"default_value": serialize_config_value(default),
			"saved_value": saved.get(name, {}).get("value"),
			"effective_value": serialize_config_value(get_config_value(name)),
			"updated_utc": saved.get(name, {}).get("updated_utc", ""),
			"has_override": name in saved,
			"is_complex": isinstance(default, (list, tuple, dict)),
			"value_type": type(default).__name__,
		}
		for name, default in sorted(_CONFIG_DEFAULTS.items(), key=lambda item: item[0].lower())
	]


class _ConfigModule(types.ModuleType):
	def __getattribute__(self, name):
		if name.startswith("_"):
			return super().__getattribute__(name)
		defaults = super().__getattribute__("__dict__").get("_CONFIG_DEFAULTS", {})
		if name in defaults:
			return get_config_value(name)
		return super().__getattribute__(name)


_CONFIG_DEFAULTS = _capture_config_defaults()
sys.modules[__name__].__class__ = _ConfigModule
